/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logisticaigu;

import Controladoras.ControladoraCliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import logisticalogica.Cliente;
import logisticalogica.Paquete;

/**
 *
 * @author ULTRA
 */
public class BuscarClientes extends javax.swing.JFrame {
    private ControladoraCliente controladoraCliente;
    private DefaultTableModel tableModel;
    private Paquete paquete; 
    private Paquete paqueteTemporal;


    /**
     * Creates new form BuscarClientes
     */
     public BuscarClientes(Paquete paqueteTemporal) {
        initComponents();
    tableModel = (DefaultTableModel) jTable1.getModel();
    controladoraCliente = new ControladoraCliente(); // Inicializa controladoraCliente
    paquete = new Paquete(); // Inicialización del paquete
    this.paqueteTemporal = paqueteTemporal;

    cargarClientesEnTabla();
    inicializarVentana();
    
    
    }
     public void mostrarVentana() {
        this.setVisible(true);
    }
     public void setPaqueteTemporal(Paquete paqueteTemporal) {
    this.paqueteTemporal = paqueteTemporal;
    // Obtener el número de paquete y mostrarlo en el JLabel Codpaquete
    if (paqueteTemporal != null) {
        Codpaquete.setText("Cod paquete: " + String.valueOf(paqueteTemporal.getCodigo_paquete()));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        numerodocclienteemisor = new javax.swing.JLabel();
        ingresardocumento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Codpaquete = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numerodocclienteemisor.setText("Numero documento:");

        ingresardocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresardocumentoActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Buscar Cliente emisor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre y Apellido", "N° documento", "N° Telefono"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre y Apellido");

        Codpaquete.setText("Cod paquete:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(numerodocclienteemisor)
                        .addGap(18, 18, 18)
                        .addComponent(ingresardocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(Codpaquete)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerodocclienteemisor)
                    .addComponent(ingresardocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codpaquete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresardocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresardocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresardocumentoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
         seleccionarClienteEmisor();

    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegistrarPaquete registrarPaquete = new RegistrarPaquete();
    registrarPaquete.setPaqueteTemporal(paqueteTemporal); // Restaura el paqueteTemporal en la nueva ventana
    registrarPaquete.mostrarVentana(); // Muestra la ventana RegistrarPaquete
    this.dispose(); // Cierra la ventana actual (BuscarClientes)
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    RegistrarCliente registrarCliente = new RegistrarCliente(paqueteTemporal);

    // Hacer visible la ventana RegistrarCliente
    registrarCliente.setVisible(true);

    // Cerrar la ventana actual (BuscarClientes)
    this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarClientesEnTabla() {
    // Limpiar la tabla antes de cargar nuevos datos
    tableModel.setRowCount(0);

    List<Cliente> clientes = controladoraCliente.obtenerTodosLosClientes();
    if (tableModel == null) {
            System.out.println("tableModel es null. Algo está mal.");
            return;
        }
    // Llenar la tabla con los datos de los clientes
    for (Cliente cliente : clientes) {
        String nombreCompleto = cliente.getNombre() + " " + cliente.getApellido();

        Object[] rowData = {
            nombreCompleto,
            cliente.getNro_documento(),
            cliente.getNro_telefono()
        };
        tableModel.addRow(rowData);
    }
}

    
    
     private void inicializarVentana() {
    jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow >= 0) {
                    // Obtener el cliente seleccionado en la tabla
                    Cliente clienteSeleccionado = obtenerClienteDesdeFilaSeleccionada(selectedRow);
                    // Realizar las acciones que necesites con el cliente seleccionado
                    // Por ejemplo, puedes usar la variable clienteSeleccionado para alguna operación.
                }
            }
        }
    });

    ingresardocumento.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            filtrarClientes();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            filtrarClientes();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            filtrarClientes();
        }
    });
    jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarClientespornombreyape();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarClientespornombreyape();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarClientespornombreyape();
            }
        });
    }


    private Cliente obtenerClienteDesdeFilaSeleccionada(int filaSeleccionada) {
    int modelRow = jTable1.convertRowIndexToModel(filaSeleccionada);
    String nombreCompleto = (String) tableModel.getValueAt(modelRow, 0); // Suponiendo que el primer valor en la fila es el nombre completo
    return obtenerClienteDesdeNombreCompleto(nombreCompleto);
}
     
    
     
     
     private void filtrarClientes() {
    String numeroDocumentoStr = ingresardocumento.getText().trim();

    if (numeroDocumentoStr.isEmpty()) {
        cargarClientesEnTabla(); // Si el campo de búsqueda está vacío, muestra todos los clientes
    } else {
        try {
            int numeroDocumento = Integer.parseInt(numeroDocumentoStr);

            // Realizar la búsqueda de clientes según los valores ingresados
            List<Cliente> clientes = controladoraCliente.filtrarClientesPorNumeroDocumento(numeroDocumento);

            // Limpiar la tabla antes de cargar nuevos datos
            tableModel.setRowCount(0);

            for (Cliente cliente : clientes) {
                String nombreCompleto = cliente.getNombre() + " " + cliente.getApellido();

                Object[] rowData = {
                    nombreCompleto,
                    cliente.getNro_documento(),
                    cliente.getNro_telefono()
                };
                tableModel.addRow(rowData);
            }
        } catch (NumberFormatException e) {
            // Manejo de error si el texto no es un número válido
            JOptionPane.showMessageDialog(null, "Ingrese un número válido para el documento.");
        }
    }
}

      private void filtrarClientespornombreyape() {
    String nombre = jTextField1.getText().trim(); // Obtener el nombre desde el campo correspondiente
    String apellido = ingresardocumento.getText().trim(); // Obtener el apellido desde el campo de número de documento

    if (nombre.isEmpty() && apellido.isEmpty()) {
        cargarClientesEnTabla(); // Si ambos campos están vacíos, muestra todos los clientes
    } else {
        // Realizar la búsqueda de clientes según los valores ingresados
        List<Cliente> clientes = controladoraCliente.filtrarNombreyApellido(nombre + " " + apellido);

        // Limpiar la tabla antes de cargar nuevos datos
        tableModel.setRowCount(0);

        for (Cliente cliente : clientes) {
            String nombreCompleto = cliente.getNombre() + " " + cliente.getApellido();

            Object[] rowData = {
                nombreCompleto,
                cliente.getNro_documento(),
                cliente.getNro_telefono()
            };
            tableModel.addRow(rowData);
        }
    }
}
   private void abrirBuscarClienteReceptor(Cliente clienteEmisorSeleccionado) {
    BuscarClienteReceptor clienteReceptor = new BuscarClienteReceptor(paqueteTemporal);

    // Establecer el paqueteTemporal en la nueva ventana
    clienteReceptor.setPaqueteTemporal(paqueteTemporal);

    // Establecer el cliente emisor y paquete temporal en la nueva ventana
    if (paqueteTemporal != null) {
        clienteReceptor.setIdClienteEmisorSeleccionado(clienteEmisorSeleccionado.getClienteID());
    }

    // Asignar el cliente emisor seleccionado al paqueteTemporal
    paqueteTemporal.setEmisor(clienteEmisorSeleccionado);

    // Llamar al método para actualizar el ID del cliente emisor en la ventana BuscarClienteReceptor
    clienteReceptor.actualizarIDClienteEmisor(clienteEmisorSeleccionado.getClienteID());

    // Hacer visible la ventana BuscarClienteReceptor
    clienteReceptor.setVisible(true);
    this.dispose(); // Cerrar la ventana actual (BuscarClientes)
}




// Modificar el método para seleccionar el cliente emisor
// Modificar el método para seleccionar el cliente emisor
public void seleccionarClienteEmisor() {
    // Verificar si paqueteTemporal está declarado y tiene datos ingresados
    if (paqueteTemporal != null && paqueteTemporal.getCodigo_paquete() != 0) {
        // Obtén la fila seleccionada en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();

        // Asegúrate de que haya una fila seleccionada
        if (filaSeleccionada >= 0) {
            // Obtén el cliente desde la fila seleccionada
            Cliente clienteSeleccionado = obtenerClienteDesdeFilaSeleccionada(filaSeleccionada);

            // Asegúrate de que el cliente seleccionado no sea nulo
            if (clienteSeleccionado != null) {
                // Mostrar un mensaje en la consola
                System.out.println("Cliente Emisor: " + clienteSeleccionado.getNombre() + " "
                        + clienteSeleccionado.getApellido() + "\nID: " + clienteSeleccionado.getClienteID());

                // Confirmar la selección
                boolean confirmacion = confirmarSeleccion();
                if (confirmacion) {
                    System.out.println("Selección confirmada. Procesar la selección aquí.");

                    // También puedes llamar a la función para abrir la ventana del cliente receptor aquí si es necesario.
                    abrirBuscarClienteReceptor(clienteSeleccionado);
                } else {
                    System.out.println("Selección cancelada. No se procesará la selección.");
                }
            } else {
                System.out.println("El cliente seleccionado es nulo.");
            }
        } else {
            System.out.println("Por favor, selecciona un cliente.");
        }
    } else {
        System.out.println("El paquete es nulo o no tiene datos ingresados. Verifica su inicialización.");
    }
}

// Agregar el método confirmarSeleccion()
private boolean confirmarSeleccion() {
    int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Estás seguro de aceptar la selección?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
    );

    return confirmacion == JOptionPane.YES_OPTION;
}

 public void mostrarInfoPaqueteTemporal(Paquete paqueteTemporal) {
        if (paqueteTemporal != null) {
            System.out.println("Código de paquete: " + paqueteTemporal.getCodigo_paquete());
            System.out.println("Domicilio de entrega: " + paqueteTemporal.getDomicilioEntrega());
            // Mostrar otros atributos según sea necesario
        } else {
            System.out.println("paqueteTemporal es nulo.");
        }
    }
private Cliente obtenerClienteDesdeNombreCompleto(String nombreCompleto) {
    // Utiliza controladoraCliente para obtener el Cliente desde el nombre completo
    // Asumo que controladoraCliente tiene un método como obtenerClientePorNombreCompleto
    return controladoraCliente.obtenerClientePorNombreCompleto(nombreCompleto);
}
    

 public Paquete obtenerPaqueteTemporal() {
        return paqueteTemporal;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codpaquete;
    private javax.swing.JTextField ingresardocumento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel numerodocclienteemisor;
    // End of variables declaration//GEN-END:variables
}
